version: 2
updates:
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(ci deps)"
  directory: "/build"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(new-cli deps)"
  directory: "/new-cli"
  schedule:
    interval: daily
  open-pull-requests-limit: 10  
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(deps)"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "Microsoft.Build"
      versions: ["16.9.0", "16.11.0"]
- package-ecosystem: github-actions
  labels:
    - "dependencies"
  commit-message:
    prefix: "(build deps)"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  labels:
    - "dependencies"
  commit-message:
    prefix: "(docs deps)"
  groups:
    remark:
      patterns:
      - "remark*"
  directory: "/"
  schedule:
    interval: monthly
